/*
Delays are primarily used to keep the auto-clicker (Selenium) running appropriately, 
since some systems and internet connections will affect how quickly Selenium can accomplish things.

You shouldn't need to change more than lag_multiplier. Increase it if you have slow internet connection or computer.
*/
delays:
  huge_max: 1200
  huge_min: 600
  lag_multiplier: 1
  large_max: 30
  large_min: 15
  med_max: 10
  med_min: 7
  micro_max: 1
  micro_min: 0.5
  small_max: 3
  small_min: 1
notifications:
  autoremote_device_names: YourPhoneName # AutoRemote is an Android app for syncing notifications (and more) across devices
  autoremote_key: YourAutoremoteKey
  autoremote_notifications: false # Set true if you filled in the above
  desktop_notifications: true
path_to_chromedriver_exe: '/../../chromedriver.exe' # Should look like "C:/....". be sure to have "chromedriver.exe" at the end
use_database: true
